### ISSUE TITLE
OverSIP as asterisk proxy

### ISSUE THREAD

**Issue by gabo05** [versatica/OverSIP#101]
Hi

I need to configure asterisk with a webphone via websockets and I found JsSIP, which recomends to use OverSIP as a proxy. I read the documentation about asterisk  and OverSIP integration (http://oversip.net/documentation/1.3.x/api/built_in_modules/outbound_mangling/), but I´m not very clear about how to configure OverSIP + asterisk. Is there a deeper documentation about?

Thanks

**Comment by ibc** [comment]
Questions in the OverSIP public mailing list, please.
BTW you can use Asterisk directly which now supports SIP over WebSocket.

**Comment by gabo05** [comment]
Ok, I'm going to write an email.

*I tried that way before but it didn't go well.

Thanks you so much.
