### ISSUE TITLE
Ubuntu 14.04 Package

### ISSUE THREAD

**Issue by wtcross** [versatica/OverSIP#68]
Currently the newest Ubuntu package offered by OverSIP is `13.04`. This is a [regular release](https://wiki.ubuntu.com/LTS) and is not currently supported. What do you think about replacing the `13.04` package with `14.04`, which is an LTS version supported through the end of 2019.

**Comment by ibc** [comment]
Ubuntu 14.04 Trusty Tahr has been added to the repository.

Thanks for reporting.

**Comment by wtcross** [comment]
Thank you for the quick response :)
