### ISSUE TITLE
Asterisk+PJSIP

### ISSUE THREAD

**Issue by cholan2100** [versatica/OverSIP#69]
I am trying to use OverSIP to handle SIPonWebsockets with Asterisk, specifically PJSIP channel driver.
The dial function errors:
-- Called PJSIP/1062/sip:lovb9ncf@192.0.2.93;transport=ws;ov-ob=0bb37700da
 WARNING[401]: pjsip:0 <?>:    tsx0x7fc90c05c ...Failed to send Request msg INVITE/cseq=16699 (tdta0x7fc90c059240)! err=171060 (Unsupported transport (PJSIP_EUNSUPTRANSPORT))

any clues?

**Comment by ibc** [comment]
please use the mailing list for questions.

BTW try this: http://oversip.net/documentation/2.0.x/api/built_in_modules/outbound_mangling/

**Comment by cholan2100** [comment]
isn't OutboundMangling enabled default in v2.0.1?

**Comment by ibc** [comment]
There is no "enable" or "disable" option. It is all up to what you code in your server.rb file.

PS: Please use the mailing list.
