### ISSUE TITLE
Oversip Installation debian packaging issue (incorrect ruby version check)

### ISSUE THREAD

**Issue by MaxMuehlbronner** [versatica/OverSIP#77]
When trying to install oversip via debian package/repositories it does not work because the package thinks the debian version of ruby is not up to date

But actually it is, the version number is different but that is something you are mentioning yourself: http://www.oversip.net/documentation/1.3.x/installation/system_requirements/

"NOTE: Debian 6.0 Squeeze, Debian 7.0 Wheezy and Ubuntu 12.04 Precise provide DEB packages called ruby1.9.1 and ruby1.9.1-dev. Despite their name, they are Ruby 1.9.2 or Ruby 1.9.3 versions"

But this does not work at all:

root@WebRTCXY:~# apt-get install oversip
Reading package lists... Done
Building dependency tree      
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 oversip : PreDepends: ruby1.9.1 but it is not installable
           PreDepends: ruby1.9.1-dev but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by lgoio** [comment]
https://github.com/lgoio/OversipRubyFix

**Comment by ibc** [comment]
It is fixed in version 2.0.2 released right now.
Thanks a lot.
