### ISSUE TITLE
 undefined method send_error_handling

### ISSUE THREAD

**Issue by neochenvip** [versatica/OverSIP#78]
when i run"oversip",i got the error:
CRIT: <launcher (master)> undefined method `send_error_handling=' for #<OverSIP::SIP::IPv4UdpServer:0x00000002322b00> (NoMethodError)
/usr/local/share/gems/gems/oversip-2.0.1/lib/oversip/sip/listeners/connection.rb:37:in `initialize'

i check the file  /usr/local/share/gems/gems/oversip-2.0.1/lib/oversip/sip/listeners/connection.rb
and comment the line
 "
#self.send_error_handling = :ERRORHANDLING_REPORT
"
then the service seems fine.

is it ok?

**Comment by ibc** [comment]
Ensure you are using EventMachine-LE rather than EventMachine.
