### ISSUE TITLE
Expected OverSIP for Ubuntu 15 and Lubuntu.

### ISSUE THREAD

**Issue by tejastank** [versatica/OverSIP#85]
Hello, Please upgrade your link.

http://www.oversip.net/documentation/2.0.x/installation/debian_and_ubuntu/

We request for below platform and for all version of debian and ubuntu and lubuntu.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

Thanks,
Tejas Tank.
SnippetBucket.com

**Comment by manwe** [comment]
Hello

I also want packages for  Windows ME. All service packs.

**Comment by ibc** [comment]
Thanks @tejastank, your request has been received. My apologies for your problems.

May you please indicate your payment details so I can start working on this?

**Comment by tejastank** [comment]
Seems @ibc  can't handle free software user's requests !!! 

Sorry, @ibc you are not right liable person whom I can allocate work ever.

**Comment by ibc** [comment]
> Seems @ibc can't handle free software user's requests !!!

Oh yes, I can and I usually do it (when they are proper issues/feedback reported by valuable people).


> Sorry, @ibc you are not right liable person whom I can allocate work ever.

Thanks, I would never be interested in working for you.

**Comment by tejastank** [comment]
Ok "reported by valuable people", so your free software have limitations.

@ibc Keep in mind, we never show interested in you other than this free software/tool, It might your nature to ask for money over raised issue for money.

Thanks,

**Comment by ibc** [comment]
> Ok "reported by valuable people", so your free software have limitations.

Oh no, it is my spare time the one who has limitations.


> @ibc Keep in mind, we never show interested in you other than this free software/tool, It might your nature to ask for money over raised issue for money.

Really, I cannot understand most of what you write. Bye.

**Comment by tejastank** [comment]
We got it, its limitation issue. Might you can't resolve things, its not big matter, might some other graceful handle it.

**Comment by ibc** [comment]
The limitation is between your keyboard and your chair.

**Comment by tejastank** [comment]
Thanks for your positive thinking for free software users. Users and community understand your great thinking for free software concept.

Thank you.

**Comment by ibc** [comment]
Please, say it loud:

"YOU PROVIDE FREE SOFTWARE SO GIVE ME MY FREE SUPPORT NOW"

**Comment by tejastank** [comment]
Grow Up. Do you think how many not loud on this !
Why does someone not go to paid product and buy it & take year support !

I hope now you understand now.

**Comment by ibc** [comment]
I'm free to choose whether I want to spend time helping undocumented users or not. And when it comes to arrogant users, I do not waste my time. Hope you understand it.

**Comment by ibc** [comment]
And please, do not give me lessons regarding how Open Source works...

**Comment by tejastank** [comment]
So you late understood, and react prior. Not an issue how you personally think on open source.
