### ISSUE TITLE
Expected Test Steps for OverSIP 

### ISSUE THREAD

**Issue by tejastank** [versatica/OverSIP#86]
After installation of OverSIP, we looking to test steps.

If possible provide test script or javascript code or anything via we can confirm and check installed things working fine at least.

Its most important require who adopt OverSIP First Time.

Thanks,
Tejas Tank

**Comment by tejastank** [comment]
What is first step we had todo after installation ?

Like how to manage sip user, create alias.

How to configure SLFPhone for test and to confirm does installation done properly or not.

Please urgent guide us to utilize this.

**Comment by ibc** [comment]
This is the bug tracker, no a forum to ask basic questions about OverSIP.

Please read the entire documentation: http://www.oversip.net/documentation/

**Comment by tejastank** [comment]
Where does your forum links ! Does any other providing forum ! 
In your READ file add forum link for stackoverflow.com, so people avoid to add their issues over here.
