### ISSUE TITLE
After Installation, how to configure Users  or SIP Accounts ?

### ISSUE THREAD

**Issue by tejastank** [versatica/OverSIP#87]
We had done installation and configuration.

Restarted after set yes.

Now let us know how to create sip users or account.

So multiple users can get their sip and able to use it .

Please guide us.

**Comment by ibc** [comment]
No. Read the documentation and stop using this bug trackers as a forum to ask everything that is already explained in the documentation:

http://www.oversip.net/documentation/

**Comment by tejastank** [comment]
Where does your forum links ! Does any other providing forum ! 
In your READ file add forum link for stackoverflow.com, so people avoid to add their issues over here.

**Comment by ibc** [comment]
In the project homepage: http://www.oversip.net

<img width="253" alt="captura de pantalla 2016-03-22 a las 19 22 44" src="https://cloud.githubusercontent.com/assets/16191/13962934/8abdd448-f063-11e5-9ae2-6f7e82376251.png">

The mailing list is the forum. I don't like stackoverflow.

**Comment by tejastank** [comment]
Add this in your read.me file too. Hopefully we take other's reference or suggestion.

**Comment by ibc** [comment]
> Add this in your read.me file too

Sorry, I do not take orders from anyone.

**Comment by tejastank** [comment]
Ok, @ibc can't adopt correction suggestion.

Its not people have to suffer.

Thanks,

**Comment by tejastank** [comment]
Example of our explanation, 
https://github.com/onsip/SIP.js/issues/301
