### ISSUE TITLE
How to setup oversip-mod-mysql ?

### ISSUE THREAD

**Issue by tejastank** [versatica/OverSIP#88]
Hello.

I am not Ruby developer, but know python, javascript and other programming.

https://github.com/versatica/oversip-mod-mysql

Like to install and configure on oversip, I had already installed it.

How to do ? Looking for instruction with all details, because I do not know gems and ruby.

Guide steps.

**Comment by ibc** [comment]
I'm so sorry. It's my fault that you don't know Ruby so I'm responsible of guiding you by free on how to setup OverSIP.

Please, let me know which language you prefer (Python, JavaScript, etc) so I will rewrite OverSIP in that language.

**Comment by tejastank** [comment]
Do you limiting your product !

People raise issue when they face issue to use it, its not always as code
bug.

No worries, we will see.




On Tuesday 22 March 2016, Iñaki Baz Castillo <notifications@github.com>
wrote:

> I'm so sorry. It's my fault that you don't know Ruby so I'm responsible of
> guiding you by free on how to setup OverSIP.
>
> Please, let me know which language you prefer (Python, JavaScript, etc) so
> I will rewrite OverSIP in that language.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/versatica/OverSIP/issues/88#issuecomment-199888610>
>


-- 
Thanks,
Tejas L Tank.
Email : Tejas.tank.mca@gmail.com
Mobile : +91 - ( 85 - 111 - 5 - 33 - 98 )
India.

**Comment by ibc** [comment]
OverSIP is not a "product" but Free Software. But if you consider it a "product" then you probably know that requesting support is not usually free.

**Comment by tejastank** [comment]
Free Software or free product, but does these all way you act and reacting, how someone even ask to support !!!

Does this way your expecting to grow your product !!! We don't care its yours decision.

Thanks to quick close the issues.

**Comment by ibc** [comment]
First of all: Have you ever read the [documentation](http://www.oversip.net/documentation/)?

I'm not here to provide free support about stuff already explained in the documentation.

**Comment by tejastank** [comment]
Thanks for unhelpful disappointing answers, Its you thinking all stuffs their.

But free software user's have their own environment and their issues even document exists.

If you can't resolve issues of free software development, I am sure you can't handle premium deals.

Thanks,

**Comment by ibc** [comment]
> If you can't resolve issues of free software development, I am sure you can't handle premium deals.

Show me your code, your projects, and how good you are providing support to your users.

**Comment by tejastank** [comment]
Do you mind ! I am not free software provider.

Do you mean providing free software mean, act like anything !!! Its not so ok.

**Comment by ibc** [comment]
> Do you mean providing free software mean, act like anything !!! Its not so ok.

:joy: so since I provide open/free software, it means that I should provide free support to any kind of question/problem regardless users haven't ever read the documentation, right?

**Comment by tejastank** [comment]
You not only born and providing free license term based software. Practical solutions more work better than politically correct answers, regardless what you think about user read document or not.

Do you think document means, everything works fine if documentation their ?

**Comment by ibc** [comment]
Bye.
