### ISSUE TITLE
Is oversip supports microsoft edge calls?

### ISSUE THREAD

**Issue by raviraja0559** [versatica/OverSIP#92]
Is oversip supports microsoft edge calls?. We would like to build an application in which we are making PSTN calls from microsoft edge. Is there any mechanism that oversip accepts the protocols which are initiated in microsoft edge. Could you please let us know.

**Comment by saghul** [comment]
OverSIP is a SIP proxy, it does not handle media. So all Microsoft Edge needs to talk to OverSIP is a WebSocket. The WebRTC / ORTC part is another story, but that's not handled by this project.
