### ISSUE TITLE
Unable to start oversip on debian 8 64-bit

### ISSUE THREAD

**Issue by kidmarche** [versatica/OverSIP#99]
when I try to run it, it gives me this error

`root@vps:~# oversip start
NOTICE: <executable> OverSIP 2.0.4 starting...
CRIT: <launcher> PID file is required (use -P or --pid option)
CRIT: <launcher> exiting with error status
`

**Comment by ibc** [comment]
Nowhere is told that you should run OverSIP in that way. Please read the documentation.

http://oversip.net/documentation/2.0.x/running_oversip/debian_and_ubuntu/
